### ISSUE TITLE
Save file error when upgrading to 1.0.3

### ISSUE THREAD

**Issue by rointep** [CryADsisAM/Sankaku-Channel-Downloader#3]
Error message when opening application:

![g2qeo](https://cloud.githubusercontent.com/assets/6323985/19764654/708d2f6e-9c44-11e6-999c-8af0fa7159e4.png)

**Comment by CryADsisAM** [comment]
Yeah, this happens because of the network error on start-up. Will fix it as soon as I get the chance.

**Comment by Kristjan-Zagar** [comment]
Yis :datboi:
